/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doancafe;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author NGAO DAY
 */
public class Form_Main extends javax.swing.JFrame {

    /**
     * Creates new form Form_Main
     */
    private static Form_Login frm_login;
    public static Connection conn;
    public static String ID;
    public static String chucvu;
    public Form_Main(Form_Login frm_login, String ID, String chucvu) {
        initComponents();
        setLocationRelativeTo(null);
        this.frm_login = frm_login;
        this.conn = frm_login.getConn();
        this.ID = ID;
        this.chucvu = chucvu;
        if (!this.chucvu.contains("admin")){
            btnThemXoa.setVisible(false);
            btnQLNS.setVisible(false);
        }
        _LoadName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDatHang = new javax.swing.JButton();
        btnCaNhan = new javax.swing.JButton();
        btnLSGD = new javax.swing.JButton();
        btnThemXoa = new javax.swing.JButton();
        btnQLNS = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 125, 57));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(23, 80, 57));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("←");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Phần Mềm Quản Lý Phúc Long");
        jLabel1.setToolTipText("");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6))
        );

        jPanel2.setBackground(new java.awt.Color(23, 125, 57));

        btnDatHang.setBackground(new java.awt.Color(23, 125, 57));
        btnDatHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDatHang.setForeground(new java.awt.Color(255, 255, 255));
        btnDatHang.setText("Đặt Hàng");
        btnDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatHangActionPerformed(evt);
            }
        });

        btnCaNhan.setBackground(new java.awt.Color(23, 125, 57));
        btnCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnCaNhan.setText("Cá Nhân");
        btnCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaNhanActionPerformed(evt);
            }
        });

        btnLSGD.setBackground(new java.awt.Color(23, 125, 57));
        btnLSGD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLSGD.setForeground(new java.awt.Color(255, 255, 255));
        btnLSGD.setText("Lịch Sử Giao Dịch");
        btnLSGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLSGDActionPerformed(evt);
            }
        });

        btnThemXoa.setBackground(new java.awt.Color(23, 125, 57));
        btnThemXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnThemXoa.setText("Thêm/Xóa");
        btnThemXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXoaActionPerformed(evt);
            }
        });

        btnQLNS.setBackground(new java.awt.Color(23, 125, 57));
        btnQLNS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQLNS.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNS.setText("Quản Lý Nhân Sự");
        btnQLNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNSActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Tên Nhân Viên: Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDatHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnCaNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemXoa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnQLNS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLSGD)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtName)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatHang)
                    .addComponent(btnCaNhan)
                    .addComponent(btnThemXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLNS)
                    .addComponent(btnLSGD))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int MouseX;
    int MouseY;
    
    private void _LoadName(){
        try {
           Statement stmt = conn.createStatement();
           ResultSet rs = stmt.executeQuery("Select hoTen from NhanVien Where ID='" + ID +"'");
           if (rs.next()){
                String name = rs.getString(1);
                txtName.setText("Tên Nhân Viên: " + name);
           }else{
               txtName.setText("Tên Nhân Viên: Không Xác Định");
           }      
        } catch (SQLException ex) {
            Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.frm_login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int ViTriX = evt.getXOnScreen();
        int ViTriY = evt.getYOnScreen();

        this.setLocation(ViTriX - MouseX, ViTriY- MouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        MouseX = evt.getX();
        MouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnQLNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNSActionPerformed
        // TODO add your handling code here:
        Form_QLNS main = new Form_QLNS(this);
        this.setVisible(false);
        main.show();
    }//GEN-LAST:event_btnQLNSActionPerformed

    private void btnCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaNhanActionPerformed
        // TODO add your handling code here:
        Form_CaNhan main = new Form_CaNhan(this);
        this.setVisible(false);
        main.show();
    }//GEN-LAST:event_btnCaNhanActionPerformed

    private void btnDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatHangActionPerformed
        // TODO add your handling code here:
        Form_DatHang main = new Form_DatHang(this);
        this.setVisible(false);
        main.show();
    }//GEN-LAST:event_btnDatHangActionPerformed

    private void btnThemXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXoaActionPerformed
        // TODO add your handling code here:
        Form_ThemXoa main = new Form_ThemXoa(this);
        this.setVisible(false);
        main.show();
    }//GEN-LAST:event_btnThemXoaActionPerformed

    private void btnLSGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLSGDActionPerformed
        // TODO add your handling code here:
        Form_LSGD main = new Form_LSGD(this);
        this.setVisible(false);
        main.show();
    }//GEN-LAST:event_btnLSGDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Main(frm_login, ID , chucvu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaNhan;
    private javax.swing.JButton btnDatHang;
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnLSGD;
    private javax.swing.JButton btnQLNS;
    private javax.swing.JButton btnThemXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
